### ISSUE TITLE
How to place a linebreak after the file header

### ISSUE THREAD

**Issue by MahatmaFatalError** [mkesting/jautodoc#10]
I have file header 
```
/* *******************************************************************************
 * bla bla bla                                                                                                                  *
 ********************************************************************************/

```
with a new line at the end.
However, when I apply it, the linebreak is not saved.

Is this a bug? How can I keep the linebreak after the file header?

**Comment by mkesting** [comment]
Sorry, but the header text will be trimmed when it is stored. So the linebreak gets lost.

But if there is already an empty line before the package declaration in your Java file, this line will be kept while adding the header. So maybe this is a possibility for you, e.g. changing the Eclipse new Java file template to add a new line before the package declaration.

**Comment by MahatmaFatalError** [comment]
Hi @mkesting thanks for the quick answer. For me, not-trimming the header seems to be the simplest solution. 
What is the rationale for trimming?
If there is a good reason for it, it should be made configurable.

**Comment by SkytAsul** [comment]
I agree with what is said above, there should be an option to keep the whole string not trimmed.

**Comment by mkesting** [comment]
I checked this and it should be possible to remove the trim without affecting existing users. A new option is not needed. But it is effort for me to create and deploy a new version. Especially when this header functionality is running since 2006 without any complaints. So I have a final question.

When I add a file header, the package declaration starts immediately on the next line like this:

```
/* *******************************************************************************
 * bla bla bla                                                                   *
 ********************************************************************************/
package mypackage.mysubpackage;
```

Is there something different in your installation or do you really need an empty line between header and package declaration? If so, what is the rationale for that?

**Comment by MahatmaFatalError** [comment]
yes, it's only about the empty line between header and package declaration. I don't know why we have it, maybe just a matter of taste.

**Comment by mkesting** [comment]
Sorry, but I will not implement this. I played around with it and it sometimes causes problems, when trying to replace the existing header.

Actually we have to separate between the raw header information and how the code should be formatted. As I already mentioned, Eclipse allows defining a template for "New Java files" where you can add a new line above the package declaration. Additionally the Eclipse Java code formatter has an option for that (Blank Lines -> Blank lines within compilation unit -> Before package declaration). Hope this helps.
