### ISSUE TITLE
JavaDoc not generated for implicitly public interface methods

### ISSUE THREAD

**Issue by heruan** [mkesting/jautodoc#2]
Seems like JAutodoc misinterprets interface methods with default public visibility as "package private", thus not generating JavaDoc for those methods if "package" visibility is disabled.

<img width="1174" alt="Screen Shot 2019-04-17 at 12 58 26" src="https://user-images.githubusercontent.com/851745/56282995-cee50f80-6110-11e9-9f47-8c247056f44c.png">

**Comment by mkesting** [comment]
Fixed with 1.14.2
