### ISSUE TITLE
Do you plan to use it for IDEA IntelliJ?

### ISSUE THREAD

**Issue by reflexdemon** [mkesting/jautodoc#4]
Hi,

Do you  plan to build a plugin for IntelliJ? I have used this plugin in the past on Eclipse and it is super useful and the IntiliJ community does not have such a clean plugin for Java Doc. Do you plan to do one for IntelliJ?

**Comment by mkesting** [comment]
No, it's not planned. JAutodoc depends a lot on the Eclipse infrastructure. It would be not easy to port it and I don't have the time to do this. So, change back to Eclipse :-)

**Comment by reflexdemon** [comment]
I will find my way back to Eclipse. Let me see of the Ant plugin is useful for me. Like I can run the ant script for a while. I will let you know how that went.
